# Generated by Django 6.1.1 on 2026-10-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('sinopsis', models.TextField()),
                ('anio_estreno', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
        ),
    ]
